
name: DeployNextjs

on:
  push:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: raoufgrera.com
        username: root
        key: ${{ secrets.BLOG_SECRET }}
        port: 22
        script: |
          cd /var/www/raoufgrera
          git pull blog master
          npm run build
          pm2 restart -0